# Generated by Django 3.2.23 on 2023-12-30 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authenticate', '0002_expiredtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredTokenProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Token',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authenticate.expiredtoken',),
        ),
        migrations.AlterModelOptions(
            name='expiredtoken',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterModelOptions(
            name='passwordlessuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
