version: '3.8'
services:
  app:
    container_name: survey-frontend
    image: survey-frontend:0.0.1
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"