# Generated by Django 3.2.23 on 2024-01-03 15:50
import os

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
    fixture_filename = 'master_data.json'
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0003_auto_20231227_1224'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
