# Generated by Django 3.2.23 on 2024-01-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_create_get_survey_answer_statistics_function'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE OR REPLACE FUNCTION public.get_survey_answer_statistics_by_user(
	IN survey_id_input bigint, 
	IN question_id_input bigint
)
    RETURNS table (
		username varchar(254),
		option_content text,
		text_content text,
		frequency bigint
	) 
    LANGUAGE 'plpgsql'
AS $BODY$
begin
	return query 
		SELECT 
			u.email AS username,
			sqo.content AS option_content, 
			sa.content AS text_content,
			COUNT(*) AS frequency
		FROM public.surveys_answer sa
			FULL OUTER JOIN public.surveys_questionoption AS sqo ON sqo.id = sa.option_id
			INNER JOIN public.authenticate_passwordlessuser AS u ON u.id = sa.answered_by_id
		WHERE sa.question_id=question_id_input AND sa.survey_id=survey_id_input
		GROUP BY 
			u.email,
			sa.content,
			sqo.id;
end;$BODY$;
        """)
    ]
