# Generated by Django 3.2.23 on 2024-03-11 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0008_auto_20240120_2350"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="question_order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="SurveySubmit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
                "unique_together": {("survey", "submitted_by", "submitted_at")},
            },
        ),
    ]
