# Generated by Django 3.2.23 on 2024-03-14 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0009_auto_20240311_1432"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("set_created_at", models.DateTimeField(auto_now_add=True)),
                ("set_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Question Sets",
                "ordering": ("-set_created_at",),
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logical_operator",
                    models.CharField(
                        choices=[
                            ("AND", "Logical Operator And"),
                            ("NOT", "Logical Operator Not"),
                            ("OR", "Logical Operator Or"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQ", "Math Operator Equal"),
                            ("LTE", "Math Operator Less Than Or Equal"),
                            ("GTE", "Math Operator Greater Than Or Equal"),
                            ("LT", "Math Operator Less Than"),
                            ("GT", "Math Operator Greater Than"),
                            ("IN", "Math Operator In"),
                            ("NIN", "Math Operator Not In"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("condition_created_at", models.DateTimeField(auto_now_add=True)),
                ("condition_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.surveyquestionset",
                    ),
                ),
                (
                    "survey_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-condition_created_at", "-condition_updated_at"),
            },
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveyquestionset",
            ),
            preserve_default=False,
        ),
    ]
